[env]
LIB = "C:\\steamaudio_4.6.1\\steamaudio\\lib\\windows-x64"
RUST_BACKTRACE = "1"

[config]
skip_core_tasks = true

[tasks.default]
description = "Build binaries and run each in a different shell"
script = [
    'cargo fmt',
    'cargo b',
    # 'cargo test',
    # 'cargo make doc',
    # 'start cmd /k "cargo r --bin client"',
    # 'start cmd /k "cargo r --bin server"',
    'cargo r --bin server',
    # "wsl bash -c './stats.sh'",
]

[tasks.doc]
command = "cargo"
args = ["doc", "--no-deps", "--bins", "--open"]